//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.12

pub mod prelude;

pub mod access_level;
pub mod organization;
pub mod session;
pub mod sim_card;
pub mod spatial_ref_sys;
pub mod user;
pub mod vehicle;
pub mod vehicle_tracker;
pub mod vehicle_tracker_last_location;
pub mod vehicle_tracker_location;
