//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.12

pub use super::access_level::Entity as AccessLevel;
pub use super::organization::Entity as Organization;
pub use super::session::Entity as Session;
pub use super::sim_card::Entity as SimCard;
pub use super::spatial_ref_sys::Entity as SpatialRefSys;
pub use super::user::Entity as User;
pub use super::vehicle::Entity as Vehicle;
pub use super::vehicle_tracker::Entity as VehicleTracker;
pub use super::vehicle_tracker_last_location::Entity as VehicleTrackerLastLocation;
pub use super::vehicle_tracker_location::Entity as VehicleTrackerLocation;
